services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api-local
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://host.docker.internal:5432/techinsights_db}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-local-user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - monitoring-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-local
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: always

networks:
  monitoring-network:
    external: true
    name: monitoring-network
