spring:
  config:
    import:
      - aws-parameterstore:/config/techinsights/prod/

cors:
  allowed-origins:
    - https://www.techinsights.shop
    - https://techinsights.shop

auth:
  oauth2:
    success-redirect-uri: https://www.techinsights.shop/
